### ISSUE TITLE
Undefined Sort.SliceStable

### ISSUE THREAD

**Issue by thiagozs** [abadojack/whatlanggo#2]
# github.com/abadojack/whatlanggo
../../.gvm/pkgsets/go1.7.3/global/src/github.com/abadojack/whatlanggo/detect.go:120: undefined: sort.SliceStable
../../.gvm/pkgsets/go1.7.3/global/src/github.com/abadojack/whatlanggo/trigrams.go:31: undefined: sort.SliceStable

**Comment by abadojack** [comment]
The function [sort.SliceStable](https://golang.org/pkg/sort/#SliceStable) was introduced in Go version 1.8. https://beta.golang.org/doc/go1.8#sort_slice. Update to Go 1.8 to use it.

**Comment by thiagozs** [comment]
Thank you. I will update for 1.8
